---

- name: Install required packages
  apt: name={{ item }} update_cache=yes state=installed force=yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - openssl
    - python-pip

- name: Add repo key
  apt_key:
    url: "https://download.docker.com/linux/debian/gpg"
    state: present

- name: Add docker.io repo
  apt_repository: repo='deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable' state=present

- name: Install docker
  apt: name=docker-ce update_cache=yes state=installed force=yes

- name: Remove docker rc
  file: path=/etc/init.d/docker state=absent

- name: Create folder for containers logs
  file: path=/var/log/containers/ state=directory

- apt: name={{ item }} state=installed
  with_items:
    - python-docker

# - name: Install python library
#   pip: name=docker-py version=1.9.0

- import_tasks: certs.yml

- name: Create systemd config
  template: src=docker.service.j2 dest=/etc/systemd/system/docker.service mode=0644
  notify: "restart docker service"
